spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.201.254.58:3306/management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1qazXSW@
    driver-class-name: com.mysql.cj.jdbc.Driver  
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 10
      #获取连接时最大等待时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      stat-view-servlet:
        #配置监控页面访问登录名称
        login-username: admin
        #配置监控页面访问密码
        login-password: admin
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 1000
    dynamic:
      datasource:
        first:  #数据源1
          url: jdbc:mysql://101.201.254.58:3306/management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: 1qazXSW@
          driver-class-name: com.mysql.cj.jdbc.Driver
        second: #数据源2
          url: jdbc:mysql://223.221.8.101:8082/ottdb1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: Cditv
          password: CD@.Ipt@v028
          driver-class-name: com.mysql.cj.jdbc.Driver
        third:  #数据源3
          url: jdbc:mysql://101.201.254.58:3306/management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: 1qazXSW@
          driver-class-name: com.mysql.cj.jdbc.Driver